server:
  port: 9527

spring:
  application:
    name: proxy

eureka:
  client:
    service-url:
      defaultZone: http://yami:123456@localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  ignored-services: user
  routes:
    userApi:
      serviceId: user
      path: /api/user/**